### ISSUE TITLE
Thymeleaf Layout 작업

### ISSUE THREAD

**Issue by ahah525** [likelion-backendschool/FinalProject_HanSeungYeon_team7#4]
## Description
- Thymeleaf layout 작업

## Todo
- [x] Thymleaf layout dependency 추가
- [x] common css, js 추가
- [x] Tymeleaf layout 적용
